# yml for production with nginx
version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
      - "jahedulislam/busybox-frontend-amd64:1.0"
    ports:
      - 4200:80


#volumes:
#  angularngixvolume:


# version: '3'
# services:
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile.dev
#     ports:
#       - "4200:4200"
#     volumes:
#       - /app/node_modules
#       - .:/app

#   tests:
#     build:
#       context: .
#       dockerfile: Dockerfile.dev

#     volumes:
#       - /app/node_modules
#       - .:/app

#     command: ["npm", "run", "test"]

